### PR TITLE
Remove duktape replace hack to support go build

### PR DESCRIPTION
**Pull request by aaronbuchwald**
This PR removes the hack to improve compilation time by replacing duktape with a local no-op version, so that go build works correctly.

The intention of this PR is to replace the current downloading of the avalanche-network-runner release with simply calling go build.

### CODE REVIEW

**Comment by gyuho** [comment]
I think once we bump up go.mod with avalanchego 1.7.10, this should pass, right?

**Comment by aaronbuchwald** [comment]
> I think once we bump up go.mod with avalanchego 1.7.10, this should pass, right?

Yup, just bumped the dependency

**Comment by gyuho** [comment]
Arr, tests are failing

```bash
=== CONT  TestFlags
panic: interface conversion: *mocks.InfoClient is not info.Client: missing method GetBlockchainID

goroutine 46 [running]:
github.com/ava-labs/avalanche-network-runner/api/mocks.(*Client).InfoAPI(0xc002d3e0f0)
	/home/runner/work/avalanche-network-runner/avalanche-network-runner/api/mocks/client.go:122 +0xb8
github.com/ava-labs/avalanche-network-runner/k8s.(*networkImpl).launchNode(0xc0002f24e0, {0x2e5dd98, 0xc002a9e780}, 0xc002ac06c0)
	/home/runner/work/avalanche-network-runner/avalanche-network-runner/k8s/network.go:427 +0xe78
github.com/ava-labs/avalanche-network-runner/k8s.(*networkImpl).launchNodes.func1()
	/home/runner/work/avalanche-network-runner/avalanche-network-runner/k8s/network.go:349 +0x73
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x97
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0xf1
FAIL	github.com/ava-labs/avalanche-network-runner/k8s	9.085s
?   	github.com/ava-labs/avalanche-network-runner/k8s/mocks	[no test files]
```

**Comment by aaronbuchwald** [comment]
Found the reason for the failing tests. The tests used to use a mock library generated in AvalancheGo and then copy-pasted into the network runner mocks directory. I updated AvalancheGo with the latest mocks since it appears the interface had changed a little bit and depending on that commit of AvalancheGo should fix the broken tests.

**Review by gyuho — APPROVED** [review]

**Pull request merged**
